services:
  web:
    image: node:latest
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "8080:5173"
    working_dir: /home/node/app
    command: sh -c "npm rebuild esbuild && npm run dev -- --host 0.0.0.0"